trigger:
- main

pool:
  name: 'Azure Pipelines'

jobs:
- job: triggerATrace
  steps:
  - script: |
      git clone https://github.com/usetrace/universal-integration.git
      npm install --prefix universal-integration

      # Passing some parameters as env vars
      export INPUT_BUILD_TIMEOUT_SECONDS=900
      export INPUT_FAIL_ON_FAILED_TRACES=true
      
      npm run usetrace --prefix universal-integration -- --projectId Zux6YTrzOwAYPAJBLnY5jfa92z4wlijK
    displayName: 'Runs the integration'

  - publish: $(System.DefaultWorkingDirectory)/output.json
    artifact: output
    displayName: 'Publish the output artifact'


- job: failedExecution
  dependsOn: triggerATrace
  condition: failed('triggerATrace')
  steps:
  - download: current
    artifact: output
    displayName: 'Download integrationOutput artifact'
  
  - script: |
      echo "Contents of output.json:"
      cat $(Pipeline.Workspace)/output/output.json | jq '.status'
      echo THE BUILD FAILED. Taking appropiate measures.
    displayName: 'Failed execution'


- job: successfulExecution
  dependsOn: triggerATrace
  condition: succeeded('triggerATrace')
  steps:
  - download: current
    artifact: output
    displayName: 'Download output artifact'

  - script: |
      echo "Contents of output.json:"
      cat $(Pipeline.Workspace)/output/output.json | jq '.status'
      echo All went as expected
    displayName: 'Successful Execution'