trigger:
- main

pool:
  name: 'Azure Pipelines'

jobs:
- job: triggerATrace
  steps:
  - script: |
      git clone https://github.com/usetrace/universal-integration.git
      npm install --prefix universal-integration

      # Passing some parameters as env vars
      export INPUT_BUILD_TIMEOUT_SECONDS=900
      export INPUT_FAIL_ON_FAILED_TRACES=true

      # Parameters can be passed by the command line too. These have precedence over env var ones
      # PASS
      #npm run usetrace --prefix universal-integration -- --traceId Zux6zjrzOwAYPAJK_cLMvZ3_xVspdHDW --browsers chrome,firefox
      
      # FAILS
      #npm run usetrace --prefix universal-integration -- --traceId ZvW-QjrzOwAYPUUKZ2_i6uzz8ZyL8cpe --browsers chrome,firefox
      
      # RUNS PROJECT
      npm run usetrace --prefix universal-integration -- --projectId Zux6YTrzOwAYPAJBLnY5jfa92z4wlijK
    displayName: 'Runs the integration'



- job: failedExecution
  dependsOn: triggerATrace
  condition: failed('triggerATrace')
  steps:
  # Process single trace artifact
  - script: |
      cat output.json | jq '.status'
      echo FAILURE!!!
    displayName: 'Failed execution'


- job: successfulExecution
  dependsOn: triggerATrace
  condition: succeeded('triggerATrace')
  steps:
  # Process single trace artifact
  - script: |
      cat output.json | jq '.status'
      echo SUCCESS!!!
    displayName: 'Successful Execution'

#
#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/TEST-*.xml'
#  displayName: 'npm install and build'
