trigger:
- main

pool:
  name: 'Azure Pipelines'

jobs:
- job: triggerATrace
  steps:
  - script: |
      git clone https://github.com/usetrace/universal-integration.git
      npm install --prefix universal-integration
      
      # Passing some parameters as env vars
      export INPUT_BUILD_TIMEOUT_SECONDS=900
      export INPUT_FAIL_ON_FAILED_TRACES=false
      
      # Run the trace and capture the output
      npm run usetrace --prefix universal-integration -- --traceId Zux6zjrzOwAYPAJK_cLMvZ3_xVspdHDW --browsers chrome,firefox > trace_output.json
      
      # Read the content and set it as an output variable
      content=$(cat trace_output.json)
      echo "##vso[task.setvariable variable=jsonContent;isoutput=true]$content"
    name: runTrace
    displayName: 'Run the integration'

- job: failedExecution
  dependsOn: triggerATrace
  condition: failed()
  variables:
    jsonContent: $[ dependencies.triggerATrace.outputs['runTrace.jsonContent'] ]
  steps:
  - bash: |
      echo "Contents of trace output:"
      echo '$(jsonContent)' | jq '.'
      echo "Failures:"
      echo '$(jsonContent)' | jq -r '.report.failures[]?.message'
      echo FAILURE!!!
    displayName: 'Failed execution'

- job: successfulExecution
  dependsOn: triggerATrace
  condition: succeeded()
  variables:
    jsonContent: $[ dependencies.triggerATrace.outputs['runTrace.jsonContent'] ]
  steps:
  - bash: |
      echo "Contents of trace output:"
      echo '$(jsonContent)' | jq '.'
      echo "-------------------------------------------------------"
      echo "Failures (should be empty):"
      echo '$(jsonContent)' | jq -r '.report.failures[]?.message'
      echo "Traces:"
      echo '$(jsonContent)' | jq -r '.traces[]'
      echo SUCCESS!!!
    displayName: 'Successful Execution'