trigger:
- main

pool:
  name: 'Azure Pipelines'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Run a test
  displayName: 'Run a multi-line script'

#
#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/TEST-*.xml'
#  displayName: 'npm install and build'
