trigger:
- main

pool:
  name: 'Azure Pipelines'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "This is a test"
#
#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/TEST-*.xml'
#  displayName: 'npm install and build'
